In [2]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2) 


| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           |  


On veut predicter les valeurs des maisons a partir de cette dataset 

In [3]:
# title Titre par défaut
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]]) #Input Data
y_train = np.array([460, 232, 178])  # reel price
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print("Features : \n" ,  X_train)
print("House price : " , y_train)



Features : 
 [[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
House price :  [460 232 178]


# Calculating the model equation  : 
$$ f_{\mathbf{w},b}(\mathbf{x}) =  w_0x_0 + w_1x_1 +... + w_{n-1}x_{n-1} + b $$
equivalent a :
$$ f_{\mathbf{w},b}(\mathbf{x}) = \mathbf{w} \cdot \mathbf{x} + b   $$ 

```
where  w and b are the parameter that we need to optimise .
( . ) c'est produit scalaire 
```

In [4]:
def cal_error(X_feat, y , w, b ) :
          # err = 0 
          # for i in  X.shape[0] :
          #           err += X_feat[i] * w[i]
          # err += b 
          

          err = float(np.dot(X_feat , w ) + b  - y)
          return err # it return an array of the  error  of  each  element

#test :

print(cal_error(X_train[1], y_train[1] , np.array([1, 1, 1 , 2]), 1))



1270.0


Cost function :

$$J(\mathbf{w},b) = \frac{1}{2m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)})^2 \tag{3}$$ 


In [5]:
def compute_cost(X, y, w, b):
    cost = 0.0

    m = X.shape[0]  # Number of training examples
    for i in range(m):

        cost += cal_error(X[i], y[i], w, b) ** 2

    cost /= (2 * m)
    return cost

print( "The cost function for  a random  parameters : " ,  compute_cost(X_train , y_train  ,w_init , b_init) )

The cost function for  a random  parameters :  1.5578904428966628e-12


On doit calculer tous ces parametres et trouver les paramatres les plus optimiser

$$\begin{align*} 
& w_j = w_j -  \alpha \frac{\partial J(\mathbf{w},b)}{\partial w_j} \tag{5}  \; & \text{for j = 0..3}\newline
&b\ \ = b -  \alpha \frac{\partial J(\mathbf{w},b)}{\partial b} \newline 
\end{align*}$$


or les derivees partielles s'ecrit sous cette forme :
$$
\begin{align}
\frac{\partial J(\mathbf{w},b)}{\partial w_j}  &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)})x_{j}^{(i)} \tag{6}  \\
\frac{\partial J(\mathbf{w},b)}{\partial b}  &= \frac{1}{m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)}) \tag{7}
\end{align}
$$

compute_gradient cette fonction calculate the cost for each row

In [6]:
def compute_gradient(X, y, w, b):
          m , n  = X.shape  # m nombre des rows , n nombre des features
          grad_w = np.zeros((n,))
          grad_b = 0.0
          for  i in  range(m) :
                    for j in range(n) :
                              grad_w[j] +=   cal_error(X[i],y[i],w,b) * X[i,j]  
                    grad_b +=  cal_error(X[i],y[i],w,b)
                    
          grad_w /=  m
          grad_b /= m 
          
          return grad_w, grad_b  
                      


In [7]:
def gradient_descent(X, y, w, b, alpha, num_iters): 
          
          j_history = []
          
          for i in range(num_iters):
                    grad_w, grad_b = compute_gradient(X, y, w, b)

                    w = w - alpha * grad_w
                    b = b - alpha * grad_b
                    
                    j_history.append( compute_cost(X, y, w, b))
                    if i% num_iters / 10 == 0:
                        print(f"Iteration {i:4d}: Cost {np.sum(j_history[-1])}")

                              
          return w, b, j_history
      
initial_w = np.zeros_like(w_init)
initial_b = 0.
w , b , j_history = gradient_descent(X_train, y_train, initial_w, initial_b, 5.0e-7, 1000)

print(f"b,w found by gradient descent: {b:0.2f},{w} ")

           
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w) + b:0.2f} , reel value: {y_train[i]}")   
    
          
          

Iteration    0: Cost 2529.4629522316304


b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19 , reel value: 460
prediction: 286.17 , reel value: 232
prediction: 171.47 , reel value: 178
